services:
  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
    network_mode: host
    command: ["redis-server","--requirepass","123456","--protected-mode", "no"]
  mongodb:
    image: mongo
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=123456
    network_mode: host
  web:
    image: mynonamevote
    # ports:
    #   - "443:443"
    #TODO:用更安全的方式传递主密钥
    environment:
      - DB.MODE=mongodb-os-redis
      - MONGODB.USER=test
      - MONGODB.PASSWORD=123456
      - main_key=${main_key}
    network_mode: host
    depends_on:
      - redis
      - mongodb